### PR TITLE
QFJ-656 - fixed logic around field validation

### PR DESCRIPTION
**Pull request by the-thing**
Change notes:

- validation logic is fixed for messages and groups

- unit tests added in quickfix.DataDictionaryTest 

- quickfix.DataDictionaryTest was refactored to JUnit 4 style to utilise ExpectedException rule

- configuration.html documentation changed for AllowUnknownMsgFields and ValidateUserDefinedFields not to be confusing and in similar style

### CODE REVIEW

**Comment by the-thing** [comment]
Hi Christoph,

You are right. For some reason TortoiseGit didn't show me configuration.html blank character changes. I see them in Eclipse. Let me fix that.

**Comment by the-thing** [comment]
Looking better.

**Comment by chrjohn** [comment]
Thank you, I will take a look at it.

**Comment by chrjohn** [comment]
Just merged, will also merge to 1.6 branch later. Thanks for the good documentation of the unit tests. :)

**Pull request merged**
