### PR TITLE
Provide an alternate default message factory to work with FIX50SP2

### PR DESCRIPTION
**Pull request by david-gibbs-ig**
This pull request provides an alternate (non-conflicting) default message factory for users of FIX50 SP2.

### CODE REVIEW

**Comment by david-gibbs-ig** [comment]
OK I didn't want to touch the standard DefaultMessageFactory but that was to avoid merges when I thought I would be maintaining this version only in a fork. So yes.

**Comment by chrjohn** [comment]
Hi @david-gibbs-ig , thanks for the PR.
Are you able to make the changes as suggested by @philipwhiuk ?
Thanks,
Chris.

**Comment by chrjohn** [comment]
Hi @david-gibbs-ig , this PR is superseded by #171 and can be closed. Do you agree?
Thanks,
Chris.

**Comment by david-gibbs-ig** [comment]
@chrjohn Yes I think so thank you.

**Pull request closed without merging**
