### PR TITLE
Created 1.5.x branch based off rev 1112.

### PR DESCRIPTION
**Pull request by justindix**

### CODE REVIEW

**Comment by chrjohn** [comment]
Wow, what do you need that for? ;)

**Comment by justindix** [comment]
I was trying to use QuickFIX/J 1.6, but I was getting some weird error
about a wrong data type on the stack or something (bad type on operand
stack), and it seemed like it might be a bug, so I downgraded to 1.5.3,
and it seems like I can place a market order now.

Is this a problem that has been fixed in a more recent version of QFJ?

Justin





On Fri, August 26, 2016 1:47 am, Christoph John wrote:
> Wow, what do you need that for? ;)
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/quickfix-j/quickfixj/pull/79#issuecomment-242644208


-- 
For by grace are ye saued, through faith, and that not of your selues: it
is the gift of God:
Not of workes, lest any man should boast.
For wee are his workemanship, created in Christ Iesus vnto good workes,
which God hath before ordeined, that we should walke in them. (Ephesians
2:8-10)

http://agora100.com

http://agora100.com/justin/TULIP.pdf

http://www.amazon.com/Omnipotent-Love-Christ-His-Bride/dp/1516819195/ref=sr_1_1?s=books&ie=UTF8&qid=1451584378&sr=1-1&keywords=omnipotent+love

**Comment by chrjohn** [comment]
You should use QFJ 1.6.2. 
https://github.com/quickfix-j/quickfixj/releases/tag/QFJ_RELEASE_1_6_2

**Comment by justindix** [comment]
Thanks.

On Mon, August 29, 2016 2:48 am, Christoph John wrote:
> You should use QFJ 1.6.2.
> https://github.com/quickfix-j/quickfixj/releases/tag/QFJ_RELEASE_1_6_2
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/quickfix-j/quickfixj/pull/79#issuecomment-243055468


-- 
For by grace are ye saued, through faith, and that not of your selues: it
is the gift of God:
Not of workes, lest any man should boast.
For wee are his workemanship, created in Christ Iesus vnto good workes,
which God hath before ordeined, that we should walke in them. (Ephesians
2:8-10)

http://agora100.com

http://agora100.com/justin/TULIP.pdf

http://www.amazon.com/Omnipotent-Love-Christ-His-Bride/dp/1516819195/ref=sr_1_1?s=books&ie=UTF8&qid=1451584378&sr=1-1&keywords=omnipotent+love

**Pull request closed without merging**
