### PR TITLE
QFJ-846 : Upload release to Maven/Sonatype

### PR DESCRIPTION
**Pull request by lburgazzoli**
To deploy to Sonatype OSS :

```
mvn clean deploy -Prelease
```

Maven settings:

```xml

<settings>

  <servers>
    <server>
      <id>ossrh</id>
      <username>sonatypeUsr</username>
      <password>sonatypePwd</password>
    </server>
  </servers>

  <profiles>
    <profile>
      <id>props</id>
      <activation>
          <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <gpg.keyname>gpgkey</gpg.keyname>
        <gpg.homerdir>/home/yourUser/.gnupg</gpg.homerdir>
        <gpg.passphrase>gpgpass</gpg.passphrase> 
      </properties>
    </profile>

</settings>
```

I've used my OSSRH account for the moment but the best would be to create a dedicated account for bamboo/travis builds so snapshots can be automatically uploaded to Sonatype OSS .

### CODE REVIEW

**Comment by chrjohn** [comment]
Thanks. Just a question out of curiosity: can anybody with a Sonatype OSS account publish snapshots for QFJ now? Or can this be restricted somehow?

**Comment by lburgazzoli** [comment]
At the moment only my sonatype account can publish quickfixj artifacts , I need to grant other people so I'm not the only one that can do so :-)

If you have a list of sonatype accounts that should have such grant let me know and I'll grant them.

**Comment by chrjohn** [comment]
I have created an account "qfjdeployment".
Thanks :)

**Comment by chrjohn** [comment]
Is there a reason why you reverted maven-compiler-plugin from 3.3 to 2.2?

**Comment by lburgazzoli** [comment]
no reason, should be a mistake wile merging from master, I will update the PR

**Comment by lburgazzoli** [comment]
OSSRH Permissions JIRA : https://issues.sonatype.org/browse/OSSRH-19686

**Comment by chrjohn** [comment]
Is the GPG signing required? Build is giving me errors:

build	29-Dec-2015 23:12:07	[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ quickfixj-parent ---
build	29-Dec-2015 23:12:07	gpg: no default secret key: No secret key
build	29-Dec-2015 23:12:07	gpg: signing failed: No secret key

**Comment by lburgazzoli** [comment]
Yes it should only required for releases, for snapshot it is optional.

You can skip it with -Dgpg.skip=true for the moment, let me have a look tomorrow on how this can be automated.

**Comment by lburgazzoli** [comment]
#56 should fix this

**Comment by chrjohn** [comment]
I tested locally and upload works. I could not get it to work with the Bamboo server because somehow it puts spaces into the command line options and hence cannot find the settings.xml. I have asked the Bamboo admins to put the file into the .m2 directory on the server.

**Comment by chrjohn** [comment]
Upload via Bamboo is working now.

**Comment by lburgazzoli** [comment]
Great, would it be possible to back port it to 1.6.x and do a release to maven central ? So we can also test if release works properly

**Comment by chrjohn** [comment]
I assume you mean Sonatype instead of Maven central? Because I did not make any config for Maven central. Or is this the same as Sonatype?

Regarding backport: I need to check the changes. Because of some unrelated changes (e.g. changed JUnit version) and QFJ version number (1.7.0-SNAPSHOT) I cannot simply cherry-pick the commits.
Maybe there is a simpler way but I'm not yet that familiar with Git(hub).

Cheers

**Comment by lburgazzoli** [comment]
If you do a release with version not ending with SNAPSHOT, the artifact will be uploaded to Sonatype staging area then to Maven central when you promote it (the plugin should do it automatically btw).

About the larger distribution, I think it has downloaded a version from sonatype, I need to investigate it

**Comment by chrjohn** [comment]
Sorry, another question before I do the release: I am not familiar with the nexus plugin. But I need to manually alter the POMs to change the version to e.g. "1.6.2" (without SNAPSHOT)? That is not something that is done automatically when using the "release" profile?

**Comment by lburgazzoli** [comment]
It doesn't with the current setup. 

If you want a fully automated solution I/you need to add the maven-release-plugin which I've not included to avoid any issues with tags and so on.

A release can be done by:
```
mvn versions:set -DnewVersion=1.2.3
mvn clean install deploy -Prelease,sign
```

If you want me to add it, let me know.

**Comment by chrjohn** [comment]
Hi, no need to add it at the moment. Just was asking. ;)
Thanks for your help so far.

**Comment by chrjohn** [comment]
Oh another question about the "sign". I remember that it failed at first (https://github.com/quickfix-j/quickfixj/pull/55#issuecomment-167888943) . So I guess I'll have to generate some keys beforehand?

**Comment by lburgazzoli** [comment]
Yes, each artifact on maven central needs to be signed


http://central.sonatype.org/pages/apache-maven.html#gpg-signed-components

After a successfully manual release, we can add the maven-release-plugin so
you can create a specific bamboo task to do a release.you can trigger
manually.

**Comment by chrjohn** [comment]
OK, I see. I'll have to talk to the Bamboo admin to check if gpg is installed and to generate the keys.

**Comment by chrjohn** [comment]
Hi @lburgazzoli , I am currently trying to build a release on my local machine. Looking good so far.
Automation via Bamboo can be done in a later step, as you suggested.
Thanks for your help and effort. :)

Cheers

**Pull request merged**
