### PR TITLE
Update getString signature in SessionSettings

### PR DESCRIPTION
**Pull request by MartyIX**
Hi,

`FieldConvertError` is not being thrown in `getString` method. 

Regards,
Martin

### CODE REVIEW

**Comment by chrjohn** [comment]
Hi @MartyIX , thanks for the PR. But could you please take a look? The build does not compile:
`/home/travis/build/quickfix-j/quickfixj/quickfixj-core/src/main/java/quickfix/mina/ssl/SSLSupport.java:[124,15] exception quickfix.FieldConvertError is never thrown in body of corresponding try statement`

**Comment by MartyIX** [comment]
@chrjohn I have fixed the compilation error. However, Travis timed out. Does Travis do that sometimes? Or is it really related to my PR?

**Comment by chrjohn** [comment]
This can happen from time to time and is not related to the PR.

**Comment by chrjohn** [comment]
Just a question: this PR was done to have the same Exceptions thrown on the getString method as it is thrown on getLong/Bool/etc..??

**Comment by MartyIX** [comment]
@chrjohn No. This PR removes `FieldConvertError` because `getString` does not employ any kind of conversion. Users using QuickfixJ should not handle exceptions needlessly as it is confusing.

Moreover, IntelliJ Idea generates separates clauses for each exception a method throws, so that code one gets is verbose like this:

```
             try {
                 propertyValue = sessionSettings.getString(sessionID, key);
            } catch (ConfigError e) {
                 e.printStackTrace();
            } catch (FieldConvertError e) {
                 e.printStackTrace();
            }
```

To summarize, this PR simply cleans up the unused exception.

**Comment by chrjohn** [comment]
Thanks, I totally misread the diff, sorry. ;)

**Pull request merged**
