### PR TITLE
Noop message store implementation

### PR DESCRIPTION
**Pull request by guidomedina**
Noop message store implementation.

### CODE REVIEW

**Comment by guidomedina** [comment]
Would it be nice to replace `MemoryStore` byt this one at some tests to make it faster?

**Comment by chrjohn** [comment]
If the tests don't rely on messages being resent (i.e. PersistMessages=N) then it might be an option.

**Comment by chrjohn** [comment]
@guidomedina The unit tests fail with this:

```
Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.016 sec <<< FAILURE! - in quickfix.NoopStoreTest
testMessageStorageOutOfSequence(quickfix.NoopStoreTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.NullPointerException

testMessageStorageMessages(quickfix.NoopStoreTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException

testRefreshableMessageStore(quickfix.NoopStoreTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException


```

**Comment by guidomedina** [comment]
Should we remove the `NoopMessageStoreTest`?
This message store doesn't follow the pattern hence all tests on it will fail.

**Comment by guidomedina** [comment]
I think I know what it is, no default constructor, adding it and testing.

**Comment by guidomedina** [comment]
Failed again, I can't figure out what's the trick, do I need to declare exceptions?
```
Tests in error: 
  NoopStoreTest>AbstractMessageStoreTest.testMessageStorageMessages:107 » NullPointer
  NoopStoreTest>AbstractMessageStoreTest.testMessageStorageOutOfSequence:124 » NullPointer
  NoopStoreTest>AbstractMessageStoreTest.testRefreshableMessageStore:160 » NullPointer
```

**Comment by chrjohn** [comment]
I'll have a look

**Comment by guidomedina** [comment]
I look these tests and I think we should delete `NoopStoreTest` as these tests expect messages to be stored where `NoopStore` is all the oppossite, sending PR.

**Comment by chrjohn** [comment]
The session that is tried to lookup is NULL in the NoopStore.refresh() method. But I don't know why this works for the other tests.

**Pull request merged**
