### PR TITLE
optimize DoubleConverter

### PR DESCRIPTION
**Pull request by leonchen83**
Benchmark                              Mode  Cnt        Score       Error  Units
DoubleConverterBenchmark.measureFast  thrpt   10  1204994.113 ± 11444.945  ops/s
DoubleConverterBenchmark.measureRaw   thrpt   10   575634.679 ±  6665.589  ops/s

### CODE REVIEW

**Comment by chrjohn** [comment]
Thanks for the PR. Would it be possible to see the code for the benchmark.
Also, there is https://github.com/quickfix-j/quickfixj/pull/34/ that I didn't yet get around to merge. It also contains a DoubleConverter optimization. Maybe you can run the same benchmark on it?
Thanks,
Chris.

**Comment by leonchen83** [comment]
pls ignore this pr, I will fix a bug in this pr. and will also upload benchmark file

**Comment by leonchen83** [comment]
Benchmark                              Mode  Cnt        Score       Error  Units
DoubleConverterBenchmark.measureFast  thrpt   10  1204420.985 ± 39386.606  ops/s
DoubleConverterBenchmark.measurePR34  thrpt   10  1369704.973 ±  4725.402  ops/s
DoubleConverterBenchmark.measureRaw   thrpt   10   602547.907 ±  4138.975  ops/s

`import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.runner.Runner;
import org.openjdk.jmh.runner.RunnerException;
import org.openjdk.jmh.runner.options.Options;
import org.openjdk.jmh.runner.options.OptionsBuilder;
import quickfix.FieldConvertError;
import quickfix.field.converter.DoubleConverter;

/**
 * Created by Baoyi Chen on 2017/1/25.
 */
public class DoubleConverterBenchmark {
    private static final String[] DATASET = new String[]{"0",".0",".1","1234","0987654321","1234567890.0987654321","-0","-1234567890.0987654321","-.0"};

    @Benchmark
    public void measureRaw() throws Exception {
        for(String str : DATASET){
            DoubleConverter.convert(str);
        }
    }

    @Benchmark
    public void measureFast() throws Exception {
        for(String str : DATASET){
        	FastDoubleConverter.convert(str);
        }
    }

    @Benchmark
    public void measurePR34() throws Exception {
        for(String str : DATASET){
            PR34DoubleConverter.convert(str);
        }
    }

    public static void main(String[] args) throws RunnerException, FieldConvertError {
        Options opt = new OptionsBuilder()
                .include(DoubleConverterBenchmark.class.getSimpleName())
                .warmupIterations(5)
                .measurementIterations(10)
                .shouldDoGC(false)
                .forks(1)
                .build();

        new Runner(opt).run();
    }
}`

**Comment by leonchen83** [comment]
I update this pr , please check

**Comment by MartyIX** [comment]
It is my understanding that your code is 10 times faster. Is there a spec for FIX double values? 

I understand that your implementation is faster because you don't trim the input string, you don't handle hex numbers, etc. Am I correct?

**Comment by chrjohn** [comment]
Hi @MartyIX ,
here should be the definition of FIX double values (float): http://www.fixtradingcommunity.org/FIXimate/FIXimate3.0/en/FIX.5.0SP2/fix_datatypes.html

**Comment by leonchen83** [comment]
Hi @MartyIX  I just translate `-?\d*(\.\d*)?` to `parseDouble` method

**Comment by MartyIX** [comment]
@leonchen83 I believe this PR should add a unit test too. To verify that it follows the spec:

> Sequence of digits with optional decimal point and sign character (ASCII characters "-", "0" - "9" and "."); the absence of the decimal point within the string will be interpreted as the float representation of an integer value. All float fields must accommodate up to fifteen significant digits. The number of decimal places used should be a factor of business/market needs and mutual agreement between counterparties. Note that float values may contain leading zeros (e.g. "00023.23" = "23.23") and may contain or omit trailing zeros after the decimal point (e.g. "23.0" = "23.0000" = "23" = "23.").
Note that fields which are derived from float may contain negative values unless explicitly specified otherwise. The following data types are based on float.

@chrjohn What do you think about the PR? Do you believe that it is backward compatible?

**Comment by chrjohn** [comment]
Hi @MartyIX ,
from briefly looking at the code it seems fine to me. We already have a unit test which should cover (hopefully ;)) all aspects: https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/test/java/quickfix/FieldConvertersTest.java method testDoubleConversion()

**Comment by leonchen83** [comment]
found a bug about IntConverter.convert, more detail pls see test case in this pr

**Comment by chrjohn** [comment]
@leonchen83 Could you elaborate on the problem? Thanks

**Comment by leonchen83** [comment]
according to `int` spec 
```java  
Sequence of digits without commas or decimals and optional sign character (ASCII characters "-" and "0" - "9" ). The sign character utilizes one byte (i.e. positive int is "99999" while negative int is "-99999"). Note that int values may contain leading zeros (e.g. "00023" = "23").
Examples:
723 in field 21 would be mapped int as |21=723|.
-723 in field 12 would be mapped int as |12=-723|
The following data types are based on int.
```

but `IntConverter.convert` method can accept a full width character e.g. １００

**Comment by leonchen83** [comment]
the root cause is `Character.isDigit` can accept a full width character

**Comment by chrjohn** [comment]
Sounds OK to me. I don't think we should change the implementation and leave it based on what `Character.isDigit` accepts.

**Comment by leonchen83** [comment]
so you mean `६७२` is a legal number?
`IntConverter.convert("६७२")`

**Comment by chrjohn** [comment]
Let me ask this way: is there a benefit to introduce a restriction to accept only ISO-LATIN digits in that method?

**Comment by leonchen83** [comment]
got the point ,thx @chrjohn

**Comment by chrjohn** [comment]
No problem, thanks for the PR. I'd like to accept it with the DoubleConverter stuff that you did.

**Pull request merged**
