### PR TITLE
QFJ-845.2

### PR DESCRIPTION
**Pull request by mingchuno**
submit a new QFJ-845 PR based on @manureno work

### CODE REVIEW

**Comment by chrjohn** [comment]
Thanks!
Do I need to merge something beforehand? Or do you have a clue why it cannot be automatically merged?

**Comment by mingchuno** [comment]
@chrjohn hang on, let me check

**Comment by mingchuno** [comment]
@chrjohn Since my forked `master` is same as your `master`, I have tried:

```
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ git merge QFJ-845 
Updating cdb01cb..1bfbbad
Fast-forward
 pom.xml                                                                                                                                               |    2 +-
 quickfixj-core/src/main/doc/usermanual/usage/configuration.html                                                                                       |    2 +-
 quickfixj-core/src/main/java/quickfix/Session.java                                                                                                    |    8 +-
 quickfixj-core/src/test/java/quickfix/MessageTest.java                                                                                                |    4 +-
 quickfixj-core/src/test/java/quickfix/SessionTest.java                                                                                                |   17 +-
 quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/resendRequestChunkSize/fix40/SequenceGapFollowedBySequenceResetWithGapFill.def |   14 +-
 quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/resendRequestChunkSize/fix41/SequenceGapFollowedBySequenceResetWithGapFill.def |   15 +-
 quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/resendRequestChunkSize/fix42/SequenceGapFollowedBySequenceResetWithGapFill.def |   16 +-
 quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/resendRequestChunkSize/fix43/SequenceGapFollowedBySequenceResetWithGapFill.def |   16 +-
 quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/resendRequestChunkSize/fix44/SequenceGapFollowedBySequenceResetWithGapFill.def |   15 +-
 quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/resendRequestChunkSize/fix50/SequenceGapFollowedBySequenceResetWithGapFill.def |   17 +-
 quickfixj-messages/pom.xml                                                                                                                            |   19 -
 quickfixj-messages/quickfixj-messages-all/pom.xml                                                                                                     |  186 ++-
 quickfixj-messages/quickfixj-messages-all/src/test/java/quickfixj/SupportForMultipleFixVersionsTest.java                                              |   61 +
 quickfixj-messages/quickfixj-messages-fix40/pom.xml                                                                                                   |   20 +-
 quickfixj-messages/quickfixj-messages-fix40/src/main/resources/FIX40.xml                                                                              |    6 +-
 quickfixj-messages/quickfixj-messages-fix41/pom.xml                                                                                                   |   20 +-
 quickfixj-messages/quickfixj-messages-fix41/src/main/resources/FIX41.xml                                                                              |    6 +-
 quickfixj-messages/quickfixj-messages-fix42/pom.xml                                                                                                   |   20 +-
 quickfixj-messages/quickfixj-messages-fix42/src/main/resources/FIX42.xml                                                                              |    8 +-
 quickfixj-messages/quickfixj-messages-fix43/pom.xml                                                                                                   |   20 +-
 quickfixj-messages/quickfixj-messages-fix43/src/main/resources/FIX43.xml                                                                              |   16 +-
 quickfixj-messages/quickfixj-messages-fix44/pom.xml                                                                                                   |   20 +-
 quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.modified.xml                                                                     | 6813 -------------------------------------------------------------------------------
 quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.xml                                                                              |   24 +-
 quickfixj-messages/quickfixj-messages-fix50/pom.xml                                                                                                   |   20 +-
 quickfixj-messages/quickfixj-messages-fix50/src/main/resources/FIX50.xml                                                                              |   18 +-
 quickfixj-messages/quickfixj-messages-fix50sp1/pom.xml                                                                                                |   20 +-
 quickfixj-messages/quickfixj-messages-fix50sp2/pom.xml                                                                                                |   20 +-
 quickfixj-messages/quickfixj-messages-fixt11/pom.xml                                                                                                  |   20 +-
 30 files changed, 438 insertions(+), 7025 deletions(-)
 create mode 100644 quickfixj-messages/quickfixj-messages-all/src/test/java/quickfixj/SupportForMultipleFixVersionsTest.java
 delete mode 100644 quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.modified.xml
```

So it should be fine

**Comment by guidomedina** [comment]
It has conflicts, that's what git is telling you, you need to pull the current master and either:
* Rebase from master (my recommendation) and resolve the conflicts locally: **git rebase master**
* Or merge master into your branch and resolve the conflicts: **git merge master**

HTH

**Comment by mingchuno** [comment]
@guidomedina I have try rebase or merge from master...no conflicts....

**Comment by guidomedina** [comment]
If github says there are conflicts, there are conflicts, you must have forgotten to pull master from QuickFixJ github, you must have two remotes on your github local repo:

Type "git remote -v" and there you should see origin -your fork- and QuickFixJ, you need to pull QuickFixJ master, then rebase from it, not your out-of-date forked master:

Here is explained how to do that: https://help.github.com/articles/syncing-a-fork/

**Comment by guidomedina** [comment]
Sorry I mislead you before, you first need to read how to add the remote:
https://help.github.com/articles/adding-a-remote/

And then how to fetch the remote and merge it or rebase from it, the use upstream as a name, I use quickfixj because it is easy for me:
https://help.github.com/articles/syncing-a-fork/

**Comment by chrjohn** [comment]
I think this can be closed now in favour of #24

**Pull request closed without merging**
