### PR TITLE
QFJ-879: Small Changes: Static compiled pattern, un-sync time and slf4j update

### PR DESCRIPTION
**Pull request by guidomedina**
**Small changes:**

- Synchronization of time in millis removed.
- Regex compiled pattern made static.
- Slf4j updated to 1.7.18

### CODE REVIEW

**Comment by chrjohn** [comment]
This is for QFJ-879, right?

**Comment by guidomedina** [comment]
Yeah, but decided to also update few minor things in a single commit.

On 29/02/16 08:48, Christoph John wrote:
>
> This is for QFJ-879, right?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quickfix-j/quickfixj/pull/63#issuecomment-190106864>.
>


-- 
Squared Financial Services Limited
www.squaredfinancial.com

Switch:       + 353 1 661 0500
Fax:          + 353 1 661 1087
Our LinkedIn: "http://www.linkedin.com/company/squared-financial-services-ltd."


Squared Financial Services Limited is regulated by the Central Bank of Ireland.
Registered Office: Custom House Plaza 2, Harbourmaster Place, IFSC, Dublin 1, Ireland. Registered No. 399289.
Directors: Youssef BARAKAT, Ronnie CULLITON, Philippe GHANEM (Swiss), Jeff GROSSMAN, Andrew MATHERS, Bachir RABBAT (Canadian).

**Comment by guidomedina** [comment]
Yeah, but decided to also update few minor things in a single commit. How do I add a comment to also affect JIRA automatically? is that configured?

**Comment by chrjohn** [comment]
If you include the issue number in the title, JIRA has a link to the pull request on the right hand side. But AFAIK you cannot make github comments appear automatically in JIRA. Or maybe you need a special plugin for that.

**Comment by guidomedina** [comment]
I have changed the synchronize block to create a proper memory barrier (on the write) operation which should clear the L1 cache, because this variable is static the synchronize should be at the class level as it is now (forced push)

**Comment by guidomedina** [comment]
Scratch that, it must be late...the synchronize was on a static method already. Re pushing.

**Comment by guidomedina** [comment]
Re-pushed with volatile, screw it, volatile will keep it correct and thread safe as writes are visible as soon as done, but TBH it is still slower than no volatile at all, though without there is a risk of not seeing the value at all if you change the time source after some other thread have started.

**Comment by chrjohn** [comment]
OK, thank you :)

**Pull request merged**
