### PR TITLE
Fixes QFJ-895 for 1.6.x

### PR DESCRIPTION
**Pull request by guidomedina**
Patched classes provided with ticket that fixes #895 for 1.6.x

### CODE REVIEW

**Comment by chrjohn** [comment]
Hi @guidomedina , after merging other SSL-related changes I had to resolve some conflicts manually.
For 1.6.x there is one failure (at least on my system):

`SSLCertificateTest.shouldFailIndividualSessionsWhenInvalidCertificatesUsed:245 No SSL exception thrown`

Does this also occur for you?
Thanks,
Chris.

**Comment by guidomedina** [comment]
There were two PRs because it was a big difficult for 1.7 and I was able to keep it very clean, try to compare the IoSessionInitiator between branches after your conflicts resolved maybe you missed something.

**Comment by guidomedina** [comment]
Testing now on 1.7.x, then I will compare both classes between branches maybe I see something different.

**Comment by chrjohn** [comment]
I have compared them but found no changes (except an unrelated change getHostName() vs. getHostString().
Probably has to do with the newly generated SSL certificates (https://github.com/quickfix-j/quickfixj/commit/508244b8c44cbf398fe6a8cff5eec78fa8da7cb2) but it is beyond me why it does not work on 1.6.x.

**Comment by guidomedina** [comment]
Could be this line an exception being transformed into another exception because this line https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/java/quickfix/mina/initiator/IoSessionInitiator.java#L163 was before outside the try, testing that change.

**Comment by guidomedina** [comment]
ok, that was it for 1.7.x, now I need to understand if I need to catch that exception or not basically from:

```
        private void connect() {
            try {
                lastReconnectAttemptTime = SystemTime.currentTimeMillis();
                SocketAddress nextSocketAddress = getNextSocketAddress();
                if (localAddress == null) {
                    connectFuture = ioConnector.connect(nextSocketAddress);
                } else {
                    // QFJ-482
                    connectFuture = ioConnector.connect(nextSocketAddress, localAddress);
                }
                pollConnectFuture();
            } catch (Throwable e) {
                handleConnectException(e);
            }
        }
```
to:

```
        private void connect() {
            lastReconnectAttemptTime = SystemTime.currentTimeMillis();
            SocketAddress nextSocketAddress = getNextSocketAddress();
            try {
                if (localAddress == null) {
                    connectFuture = ioConnector.connect(nextSocketAddress);
                } else {
                    // QFJ-482
                    connectFuture = ioConnector.connect(nextSocketAddress, localAddress);
                }
                pollConnectFuture();
            } catch (Throwable e) {
                handleConnectException(e);
            }
        }
```

WDYT? should an exception outside the try screw up what's been fixed by it?

**Pull request merged**
