### PR TITLE
Add full removeGroup method

### PR DESCRIPTION
**Pull request by philipwhiuk**
Add method that takes a boolean to also remove the count.

As per conversation on QFJ mailing list

### CODE REVIEW

**Comment by chrjohn** [comment]
Hi @philipwhiuk ,
thanks for the PR. Could you please add a tiny test? ;) I do not recall from which discussion this was. Was it "Message.getGroups() may mutate message instance"?
Thanks,
Chris.

**Comment by philipwhiuk** [comment]
It was yes - I should have time to update this today :+1:

**Comment by chrjohn** [comment]
Hi @philipwhiuk ,

I followed this up today. Given your comment on the mailing list thread I was trying to reproduce it.

> 
> So in the below example:
> 
> > System.out.println(msg.hasGroup(1));
> > System.out.println(msg.getGroups(1));
> > System.out.println(msg.hasGroup(1));
> 
> actually adds a tag, |1=0| to the message.

I could not reproduce that. Here is the output:

```
false
[]
true
9=010=167
```

The second call to `hasGroup()` returns true, but the group does not occur in the `toString()` output.
I don't know, maybe this was caused by the latest changes but I'm not sure.

Where do we go from here?

Thanks,
Chris.

**Comment by philipwhiuk** [comment]
I'll have a look and try and diagnose this some time this week - sorry I've not got back to this.

**Comment by philipwhiuk** [comment]
Closing in favour of #414

**Pull request closed without merging**
