### PR TITLE
`MessageCracker.xsl` optimization using `HashMap`

### LINKED ISSUE #577: Remove "if else" statements which is slower by nearly 7 times compared to `HashMap` in generated `MessageCracker` class
**Describe the bug**
MessageCracker generated class contains a lengthy if else statement to resolve the method call for the respective  message type.
Current logic is about 7 times slower than using HashMap key'd by message type and value as  the method reference.

I wrote a new MessageCracker.xsl which use the HashMap to resolve the method respective to message type. 

Following is the JMH benchmarking results.

### Before:

benchmarkCrackingGenerated    - use the current MessageCracker.xls generated class
benchmarkCrackingWithHashMap  use custom MessageCracker class which use HashMaps to resolve methods

Benchmark                                              Mode  Cnt         Score         Error  Units
MessageCrackerBenchmark.benchmarkCrackingGenerated    thrpt    5  10**923194**.106 ± 2861197.934  ops/s
MessageCrackerBenchmark.benchmarkCrackingWithHashMap  thrpt    5  69**723897**.515 ± 3242125.694  ops/s

### After:

benchmarkCrackingGenerated    - use the new MessageCracker.xls generated class
benchmarkCrackingWithHashMap  use custom MessageCracker class which use HashMaps to resolve methods

Benchmark                                              Mode  Cnt         Score          Error  Units
MessageCrackerBenchmark.benchmarkCrackingGenerated    thrpt    5  71**897498**.754 ± 19147681.365  ops/s
MessageCrackerBenchmark.benchmarkCrackingWithHashMap  thrpt    5  72**165054**.010 ±  4905711.116  ops/s

**To Reproduce**
Run my JMH benchmark code in my forked repo for QFJ

### Before
[Before Code Benchmark](https://github.com/isurudevj/quickfixj/blob/feature/new-message-crakcer-stage1/quickfixj-performance-regression/src/main/java/org/quickfixj/MessageCrackerBenchmark.java)

### After
[After Code Benchmark](https://github.com/isurudevj/quickfixj/blob/feature/new-message-cracker/quickfixj-performance-regression/src/main/java/org/quickfixj/MessageCrackerBenchmark.java)

**Expected behavior**
N/A

**system information:**
 - OS: [Windows11]
 - Java version [JDK8]
 - QFJ Version [3.0.0-SNAPSHOT]

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by busy-spin**
Fixes #577

### CODE REVIEW

**Comment by isurudevj** [comment]
Following is the JMH benchmarking results.


### Before:

benchmarkCrackingGenerated    - use the current MessageCracker.xls generated class
benchmarkCrackingWithHashMap  use custom MessageCracker class which use HashMaps to resolve methods

Benchmark                                              Mode  Cnt         Score         Error  Units
MessageCrackerBenchmark.benchmarkCrackingGenerated    thrpt    5  10**923194**.106 ± 2861197.934  ops/s
MessageCrackerBenchmark.benchmarkCrackingWithHashMap  thrpt    5  69**723897**.515 ± 3242125.694  ops/s

### After:

benchmarkCrackingGenerated    - use the current MessageCracker.xls generated class
benchmarkCrackingWithHashMap  use custom MessageCracker class which use HashMaps to resolve methods

Benchmark                                              Mode  Cnt         Score          Error  Units
MessageCrackerBenchmark.benchmarkCrackingGenerated    thrpt    5  71**897498**.754 ± 19147681.365  ops/s
MessageCrackerBenchmark.benchmarkCrackingWithHashMap  thrpt    5  72**165054**.010 ±  4905711.116  ops/s



**To Reproduce**
Run my JMH benchmark code in my forked repo for QFJ

### Before
[Before Code Benchmark](https://github.com/isurudevj/quickfixj/blob/feature/new-message-crakcer-stage1/quickfixj-performance-regression/src/main/java/org/quickfixj/MessageCrackerBenchmark.java)


### After
[After Code Benchmark](https://github.com/isurudevj/quickfixj/blob/feature/new-message-cracker/quickfixj-performance-regression/src/main/java/org/quickfixj/MessageCrackerBenchmark.java)

**Comment by chrjohn** [comment]
@chrjohn need to check if new code generator for FIX Latest can benefit from this.

**Comment by mrFloony** [comment]
hi, I implemented my version of MessageCracker based on HashMap, and he showed a deterioration in processing speed (~30 ms difference compared to If-Else on one message). The replacement with a Switch turned out to be a little faster (a gain of ~15 ms with the same parameters). Tested on a pre-battle stand (with slightly reduced parameters of the virtual machine and allocated memory), as a result, the implementation on the Switch went to the product stand (three weeks - normal flight)
Therefore, I would rather replace the basic MessageCracker with an implementation from Switch

**Comment by chrjohn** [comment]
@mrFloony thanks for your comment. Are you maybe able to create a benchmark as linked in https://github.com/quickfix-j/quickfixj/pull/578#issuecomment-1321206293 or as used in the quickfixj-perf-test module?

**Comment by busy-spin** [comment]
hi @mrFloony

Can let me know more details about your test. 30ms or 15ms for cracking message seems  quiet high. Even the if-else approach is much faster than that. Do you have similar JMH test for this.

**Comment by busy-spin** [comment]
> @chrjohn need to check if new code generator for FIX Latest can benefit from this.

Can let me know more details about this, I should be able to update my test. And also add comparison with switch statement vs hash map also.

**Comment by chrjohn** [comment]
> > @chrjohn need to check if new code generator for FIX Latest can benefit from this.
> 
> Can let me know more details about this, I should be able to update my test. And also add comparison with switch statement vs hash map also.

Actually this is in a different project which generates the classes from orchestrations: https://github.com/quickfix-j/quickfixj-orchestra/blob/fac2493c93f79e21ffcb3cb67cc25459dc2f467d/quickfixj-from-fix-orchestra-repository/quickfixj-from-fix-orchestra-generator/src/main/java/org/quickfixj/orchestra/CodeGeneratorJ.java#L577

**Pull request merged**
