### PR TITLE
MINA 2.2.4 update

### PR DESCRIPTION
**Pull request by chrjohn**

### CODE REVIEW

**Comment by the-thing** [comment]
@chrjohn Looking good. If this is merged I can have a look at Custom SSL filter again or maybe you want to do it. All the best in the new year.

**Comment by chrjohn** [comment]
https://github.com/advisories/GHSA-76h9-2vwh-w278

I'm not sure if we need to change something in the code. But it compiles...
Will look at it next year. :) 
Wishing you all the best in the new year.

**Comment by the-thing** [comment]
I see the vulnerability...

I meant that https://github.com/apache/mina/pull/41 change might have fixed the autostart and CustomSSLFilter from https://github.com/quickfix-j/quickfixj/pull/833 is probably not required anymore.

**Comment by chrjohn** [comment]
> @chrjohn Looking good. If this is merged I can have a look at Custom SSL filter again or maybe you want to do it. All the best in the new year.

@the-thing  if you like you can give it a go whenever you have the time. Thank you

**Pull request merged**
