### PR TITLE
Fixes QFJ-895 SSL exception caused by patch.

### PR DESCRIPTION
**Pull request by guidomedina**
@chrjohn this fixed the SSL exception for 1.7.x, see if it also fixes it for 1.6.x, it would be nice if the author of the patch could come by and comment ;-)

### CODE REVIEW

**Comment by guidomedina** [comment]
Testing for 1.6.x after cherry-picked

**Comment by guidomedina** [comment]
@chrjohn yeap, same for 1.6.x, all tests passed too, I don't think leaving these two lines out of the try should affect the patch, but it is definitely fixing the SSL tests so I guess that's the correct change.

**Comment by guidomedina** [comment]
You only need to cherry pick this PR into 1.6.x, it merges without conflicts.

**Comment by guidomedina** [comment]
I like how it takes almost 2 less minutes testing on 1.7.x than 1.6.x, I think that's because of the `MessageDecoder` using `switch(String)` with 50+ cases (message type)

**Comment by guidomedina** [comment]
Closing, that test fails sometimes, it just failed for me again, then next time it didn't.

**Comment by chrjohn** [comment]
Yes, same for me. Sometimes it is failing. Strange.

**Pull request closed without merging**
