### PR TITLE
Fixes QFJ-895 for 1.7.x and bump plugin versions

### PR DESCRIPTION
**Pull request by guidomedina**
Bump plugin versions, all tests passed, everything generated pretty fast which makes me think `javadoc-plugin` got better, or maybe just a placebo effect.

### CODE REVIEW

**Comment by guidomedina** [comment]
@amichair can you please take a look at:

http://www.quickfixj.org/jira/browse/QFJ-895

I was able to patch 4 out of 5 files with https://github.com/quickfix-j/quickfixj/pull/76/commits/b0b35b54ffa43fb03225a84f16cbeba72fc30cf9 if you could shed some light as `IoSessionInitiator` has many conflicts after SSL refactor which I couldn't crack.

**Comment by guidomedina** [comment]
@chrjohn @amichair I'll retry tomorrow, this is what happens when you try to code after work, I just noticed I can do it _-I think-_ but will do it tomorrow after lunch that I'm home early.

**Comment by guidomedina** [comment]
@chrjohn @amichair done, it would be nice if the original author of the patched classes could verify this commit.

**Comment by chrjohn** [comment]
Thanks Guido! :)

**Pull request merged**
