### PR TITLE
Queues drain tweak and bump plugin versions.

### PR DESCRIPTION
**Pull request by guidomedina**
@chrjohn please review and cherry pick if you feel is not good, one change is the closeOnFlush and the other pom changes.

### CODE REVIEW

**Comment by guidomedina** [comment]
@chrjohn my reasoning is that `closeOnFlush` would leave the behavior untouched as it was with `closeNow()` and `mina-core 2.0.13` which is why I'm against changing drastically to the new behavior, it can cause some threads to block which can be really hard to reproduce and lead to problems in production.

**Comment by guidomedina** [comment]
All tests passed for me again with these changes:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] QuickFIX/J Parent .................................. SUCCESS [  0.046 s]
[INFO] QuickFIX/J Code Generator Maven Plugin ............. SUCCESS [  1.205 s]
[INFO] QuickFIX/J Dictionary Generator .................... SUCCESS [  0.420 s]
[INFO] QuickFIX/J Core engine ............................. SUCCESS [14:06 min]
[INFO] QuickFIX/J Message classes for various FIX specs ... SUCCESS [  0.001 s]
[INFO] QuickFIX/J Message classes for FIX 4.0 ............. SUCCESS [  0.231 s]
[INFO] QuickFIX/J Message classes for FIX 4.1 ............. SUCCESS [  0.232 s]
[INFO] QuickFIX/J Message classes for FIX 4.2 ............. SUCCESS [  0.213 s]
[INFO] QuickFIX/J Message classes for FIX 4.3 ............. SUCCESS [  0.198 s]
[INFO] QuickFIX/J Message classes for FIX 4.4 ............. SUCCESS [  0.292 s]
[INFO] QuickFIX/J Message classes for FIX 5.0 ............. SUCCESS [  0.219 s]
[INFO] QuickFIX/J Message classes for FIX 5.0 SP1 ......... SUCCESS [  0.207 s]
[INFO] QuickFIX/J Message classes for FIX 5.0 SP2 ......... SUCCESS [  0.200 s]
[INFO] QuickFIX/J Message classes for FIXT 1.1 ............ SUCCESS [  0.189 s]
[INFO] QuickFIX/J Message classes for all FIX specs ....... SUCCESS [  0.191 s]
[INFO] QuickFIX/J Examples ................................ SUCCESS [  0.002 s]
[INFO] QuickFIX/J Examples - Executor ..................... SUCCESS [  0.250 s]
[INFO] QuickFIX/J Examples - Order Match .................. SUCCESS [  0.207 s]
[INFO] QuickFIX/J Examples - Banzai ....................... SUCCESS [  0.393 s]
[INFO] QuickFIX/J All runtime modules ..................... SUCCESS [  0.082 s]
[INFO] QuickFIX/J Distribution ............................ SUCCESS [  0.028 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:11 min
[INFO] Finished at: 2016-10-17T11:45:01+01:00
[INFO] Final Memory: 145M/1681M
[INFO] ------------------------------------------------------------------------
```

**Comment by chrjohn** [comment]
Please see comment here
https://github.com/quickfix-j/quickfixj/pull/80#issuecomment-254169620

**Comment by guidomedina** [comment]
@chrjohn ok, I have undone these changes, renamed this PR and now it has one commit with plugin versions and two small changes not related to MINA:

Some queues were being drained to local blocking queues, instead they can be drained to lists, no thread safety is needed as such lists local variables which never leave the scope in which they are created.

**Comment by chrjohn** [comment]
Thanks, @guidomedina 
Re queues vs. lists: :thumbsup:

**Pull request merged**
