### PR TITLE
QFJ-950 reject garbled messages

### PR DESCRIPTION
**Pull request by chrjohn**
Provide configuration to have garbled messages rejected instead of ignored.

### CODE REVIEW

**Comment by philipwhiuk** [comment]
I feel like the documentation needs to be clearer in terms of what a Garbled Message is vs an Invalid Message, especially as the code seems to use `MessageUtils.newInvalidMessageException()` to handle a garbled message yet we have two properties, RejectInvalidMessage and RejectGarbledMessage. Perhaps we should have a table with some examples and the output (procesed, dropped, rejected?) - e.g [but probably not accurate]:

| Issue  | RejectInvalidMessage | RejectGarbledMessage | Output |
| ------------- | ------------- |------------- |------------- |
| Missing mandatory field  | N | N | Ignored |
|   | N  | Y | Ignored |
|   | Y | N | Ignored |
|   | Y  | Y | Rejected |
| Field with no data  | N | N | Ignored |
|   | N  | Y | Ignored |
|   | Y | N | Ignored |
|   | Y  | Y | Rejected |
| Incorrect repeating group count  | N | N | Processed |
|   | N  | Y | Ignored |
|   | Y | N | Ignored |
|   | Y  | Y | Rejected |
| Repeating group count not a number  | N | N | Ignored |
|   | N  | Y | Ignored |
|   | Y | N | Ignored |
|   | Y  | Y | Rejected |

**Comment by chrjohn** [comment]
Hi @philipwhiuk ,
thanks for your comment. Initially I planned to use RejectInvalidMessage but that was already taken. :-( So I went for garbled message because all cases that were signalled with a InvalidMessage Exception were ignored and the FIX spec states that garbled messages should be ignored.
However, I think an update to the documentation is a good idea! I will add such a table.
Thanks,
Chris.

**Comment by chrjohn** [comment]
Hi @philipwhiuk ,
I have added some explanations to the documentation. Maybe you could review it? I did not go with the table structure but decided to give a little background information on the two settings (data dictionary validation failure vs. FIX protocol failure).
Let me know what you think.

Thanks,
Chris.

**Comment by philipwhiuk** [comment]
Looks good to me :+1:

**Comment by chrjohn** [comment]
Great, thanks.

**Pull request merged**
