### PR TITLE
Fix for dropped logout message issue (1.6.x)

### PR DESCRIPTION
**Pull request by traggatt**
Backport of PR #130 for QFJ 1.6.x branch.

### CODE REVIEW

**Comment by traggatt** [comment]
Thanks again.

**Comment by chrjohn** [comment]
You're welcome.

**Comment by traggatt** [comment]
Can I take it from the existence of a 1.6.5 milestone that a release is now planned/imminent? 😋

**Comment by chrjohn** [comment]
No, just added a milestone to have everything organized. :)
As said, 1.7.0 has priority now. If there are any major issues with the 1.6.4 release then there **might** be a 1.6.5 release. Up to that point you could simply download the 1.6.x branch and build it with
`mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true`
and you're set. :)

**Pull request merged**
