### PR TITLE
QFJ-853 Add ability to modify the Proxool JDBC connection pool via session settings

### PR DESCRIPTION
**Pull request by RockManJoe64**
I've made some modifications to allow the Proxool data source be configurable via the session settings file. The previous default values are kept, in case the developer does not specify these settings.

The additional JDBC properties are specific to those properties that had been hard coded. In the future, more properties can be defined to further tune the data source.

### CODE REVIEW

**Comment by RockManJoe64** [comment]
Hi Christoph,

Apologies been so busy, just saw your comments tonight (after 6 months)!
I've made the proposed changes to documentation, and corrected the passing arguments in the JdbcUtil.java. 

Please review and consider my pull request.

Thanks!

Jose

**Comment by RockManJoe64** [comment]
I committed some more changes to my master. Not sure if this endangers my pull request.
I opened up some getters and setters in the GenerateMojo. I needed to have more control over Message/FIeld class generation for custom protocols (CME, ICE, etc). One file was modified: GenerateMojo. Can you please review when you get a chance?

Thanks,

Jose

**Comment by chrjohn** [comment]
Hi @RockManJoe64 
some of the parameters in the code do not match the configuration.html but I will fix that later.
Thanks for the PR :)

**Comment by chrjohn** [comment]
https://github.com/quickfix-j/quickfixj/commit/f7c4e7ec1d4920718537e9e69aa996ca7987401d

**Pull request merged**
