### PR TITLE
Fix orchestra

### PR DESCRIPTION
**Pull request by david-gibbs-ig**
Here is a pull request for Support for FIX Latest #317. It is for discussion. 

It generates the FIX Dictionary from the FIX Latest orchestration - and applies some transformations to work around the small number of incompatibilities with QFJ. Some of these will in due course be corrected by FTC.

Please see the readmes.

I think that supporting FIX Latest may require incrementing the major release number of QFJ because of the way that QFJ shares the generation of classes for Fields between FIX Versions.

FIX Latest uses more terse descriptions.
example :
newSingle.setField(new HandlInst(HandlInst.MANUAL_ORDER_BEST_EXECUTION)); becomes
newSingle.setField(new HandlInst(HandlInst.MANUAL_ORDER));

These are very easy code changes to make but they are an incompatibility.
Please note that Memory requirements and build time for FIX Latest javadoc are both significant.

### CODE REVIEW

**Comment by chrjohn** [comment]
Hi @david-gibbs-ig , thanks for the PR. This will definitely be useful.  :+1: 
Will take some time to review, though. Just a question: was there a specific reason to deviate from the `quickfixj-` naming scheme for the module? No big thing, just asking. 
Thanks again.

**Comment by david-gibbs-ig** [comment]
Hi Christophe, it might be better fit if the module was named "quickfixj-from-orchestra", I just did not think of it.  I'm sure this needs discussion and many refinements. It takes a long time to build which I think is a real concern, I have trouble with the tests in my local build environment which makes it is very hard to verify the build. It looks like Travis still won't build it, maybe there can be better luck with the github build tools.

**Comment by chrjohn** [comment]
Will there be a follow up PR to this? Anything I can help you with?

**Comment by david-gibbs-ig** [comment]
Thanks I have been working on it. I may have figured out what was making the build fail tonight. I will certainly ask for help and it would be good to discuss the potential changes with you if possible.

**Comment by david-gibbs-ig** [comment]
Hi figured out how to get the build further but then hit this limit at 50 minutes. "The job exceeded the maximum time limit for jobs, and has been terminated." I may need a little help getting the builds running in github actions instead.

**Comment by david-gibbs-ig** [comment]
> Will there be a follow up PR to this? Anything I can help you with?

Thanks, here is new PR that is pretty clean, see also comments on the issue and PR. Maybe we could have a call to discuss. PS have you considered using gitter, https://gitter.im/home . I only just found out about it.

https://github.com/quickfix-j/quickfixj/pull/333

thanks

**Pull request closed without merging**
