### PR TITLE
`FileStore` message length fix

### PR DESCRIPTION
**Pull request by the-thing**
Fixes https://github.com/quickfix-j/quickfixj/issues/650

### CODE REVIEW

**Comment by chrjohn** [comment]
Hi @the-thing , thanks for the quick fix. :)

**Comment by the-thing** [comment]
@chrjohn No problem. Some small post merge issues to fix.

**Comment by chrjohn** [comment]
@the-thing ready to merge?

**Comment by the-thing** [comment]
@chrjohn Seems like it. Go for it.

**Pull request merged**
