### PR TITLE
QFJ-845

### PR DESCRIPTION
**Pull request by manureno**
Pull request for QJF-845, it includes QFJ-803 which is a pre-requisite

### CODE REVIEW

**Comment by chrjohn** [comment]
Thanks for the pull request.
However, what I don't understand is that the SupportForMultipleFixVersionsTest does not throw any errors when I run it in my environment (without merging your other changes).

**Comment by kimptoc** [comment]
Tried to do a mvn package on this PR, but it fails (works ok on my fork :( ) - is there a new dependancy or something I need extra ?

Thanks.

[INFO] ------------------------------------------------------------------------
[INFO] Building QuickFIX/J Message classes for FIX 4.3 1.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/quickfixj/quickfixj-codegenerator/maven-metadata.xml
[WARNING] Could not transfer metadata org.quickfixj:quickfixj-codegenerator/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: unknown error
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] QuickFIX/J Parent .................................. SUCCESS [  0.005 s]
[INFO] QuickFIX/J Code Generator Maven Plugin ............. SUCCESS [  4.342 s]
[INFO] QuickFIX/J Dictionary Generator .................... SUCCESS [  1.045 s]
[INFO] QuickFIX/J Core engine ............................. SUCCESS [01:25 min]
[INFO] QuickFIX/J Message classes for various FIX specifications SUCCESS [  0.001 s]
[INFO] QuickFIX/J Message classes for FIX 4.0 ............. SUCCESS [  2.061 s]
[INFO] QuickFIX/J Message classes for FIX 4.1 ............. SUCCESS [  1.913 s]
[INFO] QuickFIX/J Message classes for FIX 4.2 ............. SUCCESS [  2.404 s]
[INFO] QuickFIX/J Message classes for FIX 4.3 ............. FAILURE [ 35.365 s]
[INFO] QuickFIX/J Message classes for FIX 4.4 ............. SKIPPED
[INFO] QuickFIX/J Message classes for FIX 5.0 ............. SKIPPED
[INFO] QuickFIX/J Message classes for FIX 5.0 SP1 ......... SKIPPED
[INFO] QuickFIX/J Message classes for FIX 5.0 SP2 ......... SKIPPED
[INFO] QuickFIX/J Message classes for FIXT 1.1 ............ SKIPPED
[INFO] QuickFIX/J Message classes for all FIX specifications SKIPPED
[INFO] QuickFIX/J Examples ................................ SKIPPED
[INFO] QuickFIX/J Examples - Executor ..................... SKIPPED
[INFO] QuickFIX/J Examples - Order Match .................. SKIPPED
[INFO] QuickFIX/J Examples - Banzai ....................... SKIPPED
[INFO] QuickFIX/J All runtime modules ..................... SKIPPED
[INFO] QuickFIX/J Distribution ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min
[INFO] Finished at: 2015-05-15T08:59:10+01:00
[INFO] Final Memory: 27M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Error resolving version for plugin 'org.quickfixj:quickfixj-codegenerator' from the repositories [local (/Users/kimptoc/.m2/repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginVersionResolutionException

**Comment by chrjohn** [comment]
Hmm, build works for me. Strange. The code generatrór is a Maven plugin which is built before the core engine. I also don't understand why FIX4.0-4.2 works?!

**Comment by kimptoc** [comment]
Weird indeed - I have merged my fork with upstream and that still builds ok, and re-downloaded the PR and it still fails - was using Java8, also fails in same spot with Java6 - this is on OSX Yosemite.

Could you make your package files available somewhere - I can then try my tests with them and see if it helps/fixes my multi-version issues :)

**Comment by chrjohn** [comment]
Nevermind, after testing again it also did not work for me. ;) Probably was testing on the wrong branch. However, the problem seems to be that some of the  quickfixj-messages/quickfixj-messages-fix-xx/pom.xml files are missing the version for the quickfixj-codegenerator plugin. After adding the version the build works. Ex:

`
 <plugin>
                <groupId>org.quickfixj</groupId>
                <artifactId>quickfixj-codegenerator</artifactId>
                <version>${project.version}</version>
`
... and so on

**Comment by chrjohn** [comment]
@manureno : may I ask why you are using fork=true and the increased memory? For me it works with the default config and with your config it is a) very very slow and b) eventually fails when compiling quickfixj-messages-all.

**Comment by manureno** [comment]
@chrjohn 
*  _"Is there a reason why it says "quickfix.fixt42"? It's the same for FIX4.1."_ 
no, it's  a mistake

* _"the SupportForMultipleFixVersionsTest does not throw any errors when I run it in my environment (without merging your other changes)."_
After running the test on the master with a full rebuild (including the erasing the local maven repo) the following errors are raised : 
image
Can you please try to rebuild after cleaning local maven repo ?

* _"why you are using fork=true and the increased memory?"_
I could not reach the end of the build due to OutOfMemory error during compilation phase. 
This look to be environment specific behavior : I'll check if there is a way to go through this without affecting the global pom

**Comment by mingchuno** [comment]
I cannot package either with clean checkout the branch `QJF-845` (yes, not `QFJ-845` which don't include that 2 fix commits):
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] QuickFIX/J Parent ................................. SUCCESS [0.001s]
[INFO] QuickFIX/J Code Generator Maven Plugin ............ SUCCESS [1.733s]
[INFO] QuickFIX/J Dictionary Generator ................... SUCCESS [1.117s]
[INFO] QuickFIX/J Core engine ............................ SUCCESS [44.855s]
[INFO] QuickFIX/J Message classes for various FIX specifications  SUCCESS [0.001s]
[INFO] QuickFIX/J Message classes for FIX 4.0 ............ SUCCESS [1.857s]
[INFO] QuickFIX/J Message classes for FIX 4.1 ............ SUCCESS [2.191s]
[INFO] QuickFIX/J Message classes for FIX 4.2 ............ SUCCESS [3.819s]
[INFO] QuickFIX/J Message classes for FIX 4.3 ............ SUCCESS [6.540s]
[INFO] QuickFIX/J Message classes for FIX 4.4 ............ SUCCESS [16.665s]
[INFO] QuickFIX/J Message classes for FIX 5.0 ............ SUCCESS [28.109s]
[INFO] QuickFIX/J Message classes for FIX 5.0 SP1 ........ SUCCESS [36.549s]
[INFO] QuickFIX/J Message classes for FIX 5.0 SP2 ........ SUCCESS [42.893s]
[INFO] QuickFIX/J Message classes for FIXT 1.1 ........... SUCCESS [1.513s]
[INFO] QuickFIX/J Message classes for all FIX specifications  FAILURE [7:05.165s]
[INFO] QuickFIX/J Examples ............................... SKIPPED
[INFO] QuickFIX/J Examples - Executor .................... SKIPPED
[INFO] QuickFIX/J Examples - Order Match ................. SKIPPED
[INFO] QuickFIX/J Examples - Banzai ...................... SKIPPED
[INFO] QuickFIX/J All runtime modules .................... SKIPPED
[INFO] QuickFIX/J Distribution ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:13.462s
[INFO] Finished at: Mon May 18 16:08:05 HKT 2015
[INFO] Final Memory: 23M/441M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project quickfixj-messages-all: Compilation failure -> [Help 1]
```

**Comment by chrjohn** [comment]
@manureno Thanks, I now managed to reproduce the error with your unit test on the 1.6.x branch.

**Comment by mingchuno** [comment]
managed to package the branch with below removed as @chrjohn said:
```
<fork>true</fork>
<meminitial>128m</meminitial>
<maxmem>756m</maxmem>
```

**Comment by mingchuno** [comment]
btw, another issue occur when using this build in my code.
```
Caused by: quickfix.DataDictionary$Exception: Could not find data dictionary: FIX44.xml
	at quickfix.DataDictionary.read(DataDictionary.java:823)
	at quickfix.DataDictionary.<init>(DataDictionary.java:103)
	at quickfix.DefaultSessionFactory.getDataDictionary(DefaultSessionFactory.java:328)
	at quickfix.DefaultSessionFactory.createDataDictionary(DefaultSessionFactory.java:224)
	at quickfix.DefaultSessionFactory.processPreFixtDataDictionary(DefaultSessionFactory.java:214)
	at quickfix.DefaultSessionFactory.create(DefaultSessionFactory.java:120)
	at quickfix.mina.SessionConnector.createSession(SessionConnector.java:141)
	at quickfix.mina.initiator.AbstractSocketInitiator.createSessions(AbstractSocketInitiator.java:162)
```

This is due to the change in [here](https://github.com/manureno/quickfixj/commit/59bb0097b680fb7266893386bcdc8a1971776dba#diff-909be4f78b6b431bf134e110c26eeebdL180)

I will try to fix the issue I have found and submit a new PR

**Comment by mingchuno** [comment]
I still cannot solve the problem above after the [commit](https://github.com/mingchuno/quickfixj/commit/1bfbbad511fc33798843b909b782612dd7438b2b), should be the issue in commit 59bb0097 ?

**Comment by chrjohn** [comment]
@mingchuno Does the error occur at runtime? I don't think that is has to do with the build. You should just make sure that the relevant JAR file is in your classpath (either messages-all or messages-fix44).

**Comment by mingchuno** [comment]
@chrjohn The error occur at runtime. I am working on a Trading Engine prototype which is working fine in v1.6.0 except with the bug in QFJ-845 which I cannot `new quickfix.fix44.NewOrderSingle()`. But when I update to this branch, I fail to init the `SocketInitiator` which `Caused by: quickfix.DataDictionary$Exception: Could not find data dictionary: FIX44.xml`

And of course, I have added the depenency
`"org.quickfixj" % "quickfixj-all" % "1.7.0-SNAPSHOT"`

**Comment by chrjohn** [comment]
If everything else fails you could at least put the data dictionary into an arbitrary directory and change your session settings accordingly, i.e. change the DataDictionary configuration accordingly.

**Comment by mingchuno** [comment]
@chrjohn Yes of course this is a work around. But I want to find the reason behind and make sure this does not affect everyone.

**Comment by chrjohn** [comment]
@mingchuno What does your session config look like?

**Comment by mingchuno** [comment]
@chrjohn  Here is my cfg, I have mark some field with `hidden` for security reason:
```
[default]
FileStorePath=target/data/hidden
FileLogPath=target/log/hidden
FileLogHeartbeats=Y
FileIncludeMilliseconds=Y
FileIncludeTimeStampForMessages=Y
ConnectionType=initiator
TargetCompID=HIDDEN
SocketConnectHost=HIDDEN
TimeZone=America/New_York
StartTime=17:05:30
EndTime=17:05:00
StartDay=FRI
EndDay=FRI
HeartBtInt=5
ReconnectInterval=5
RejectInvalidMessage=N

[session]
SenderCompID=Q003
ResetOnLogon=Y
BeginString=FIX.4.4
SocketConnectPort=HIDDEN

[session]
SenderCompID=T003
ResetOnLogon=Y
SocketUseSSL=Y
BeginString=FIX.4.4
SocketConnectPort=HIDDEN
```

**Comment by mingchuno** [comment]
and I have try the work around by copy FIX44.xml into my project and add `DataDictionary=FIX44.xml` and of cause it work.

**Comment by chrjohn** [comment]
OK. Until now I was not aware that it works without even specifying the DataDictionary option.
If it works on another build then it might be an error with the current build, as you said.

**Comment by mingchuno** [comment]
@chrjohn Yes, I have try the build in tag `QFJ_RELEASE_1_6_0`,  `SocketInitiator` can init w/o both `UseDataDictionary` and `DataDictionary` set (and I think by default it will look at the quickfix/j jar and find the default `FIXmm.xml` needed. While changing to this branch (to be exact, I build from this [commit](https://github.com/mingchuno/quickfixj/commit/1bfbbad511fc33798843b909b782612dd7438b2b), it fail to found the FIX44.xml

**Comment by guidomedina** [comment]
fork=true? Remove it and test, did you guys read what fork=true does? Does fork-join rings the bell?, you might be building the whole stuff in parallel causing one module to start building before its dependency is done.

**Comment by guidomedina** [comment]
I just saw fork=true has been there for a long time so, ignore my previous comment.

**Comment by guidomedina** [comment]
No, don't ignore my comment, fork=true was added in a pull request before this one: https://github.com/quickfix-j/quickfixj/commit/0c945fcd20bdd9dbd246374cb5deac776203d65c

**Comment by mingchuno** [comment]
@guidomedina you can take a look on my fork of this fix [here](https://github.com/mingchuno/quickfixj/commits/QFJ-845). I did remove the `fork=true` and build did work

**Comment by guidomedina** [comment]
I suspected it was only the `fork=true` which triggered parallel compilers, testers and class loaders, the memory parameters are OK though.

**Comment by mingchuno** [comment]
anyone have update on this issue?

**Comment by chrjohn** [comment]
@kimptoc Did this PR work for you?

**Comment by kimptoc** [comment]
Not tried again yet. Was it updated, will it build now or do I need to tweak the build?  Will try Tuesday evening

**Comment by chrjohn** [comment]
You still need to tweak the build.
See this comment: https://github.com/quickfix-j/quickfixj/pull/24#issuecomment-102979991
And this one: https://github.com/quickfix-j/quickfixj/pull/24#issuecomment-102527613

**Comment by mingchuno** [comment]
@chrjohn should I submit a new PR?

**Comment by kimptoc** [comment]
Ok - build tweaked and built - will try it out tomorrow :)

**Comment by kimptoc** [comment]
Hi,

I have run my mixed version tests with this build and it all works, with a little tweak - the FIX*.xml files were not in the built (-all) jar,so I added them afterwards.

Presumably they would be in the final build?  No big deal if not, can add them to my classpath.

Many Thanks,
Chris

**Comment by chrjohn** [comment]
Hi,

thanks for testing. I assume the fact that the data dictionaries were not in the JAR file is the reason why @mingchuno had the problems finding the data dictionary in the classpath.
I hope there is a way to include the DDs in the JAR and still have the mixed version stuff working...

**Comment by mingchuno** [comment]
@chrjohn ok, I will submit a new PR

**Comment by manureno** [comment]
Hello,

Can you please review the latest commits on this branch which include :

 - Starting point : Initial pull Request #24
 - Rebased to quickfixj/master up to july 6th (commit #f4c17946eeaaf9012ee9155a579df77b85eaf0aa)
 - Includes a full revert of QFJ-844
	commit ea46c51994224f2f914e2aa7bcb51b63edd9984d from guidomedina
	commit 741ef9eb29d113addf45005f8e42d1b0e63ef2bb from manureno
 - Includes fixes for feedback from chrjohn
		quickfixj-messages/quickfixj-messages-fix41/pom.xml
			Replace "quickfix.fixt41" with "quickfix.fix41"
		quickfixj-messages/quickfixj-messages-fix42/pom.xml
			Replace "quickfix.fixt42" with "quickfix.fix42"
		
- Includes fixes for issue in code generation raised by kimptoc
	Add <version>${project.version}</version> block that were missing in code generator configurations
	
- Include missing dictionary files in the quickfixj-messages-all file (raised by mingchuno)
	NB1: Packaging is reproduce as-is, including 
			- both FIX44.xml and FIX44.modified.xml
			- both FIX50SP1.xml and FIX50SP1.modified.xml
			- both FIX50SP2.xml and FIX50SP2.modified.xml
		The *.modified.xml file being  used for code generation.
	NB2 : Any historic context for maintaining 2 versions 2 versions of the same dictionaries would be appreciated.

The current status of the branch is intended to contain the various feedbacks and to be mergeable.
Please let me know if it can provide a solution to the classes incompatibility issue.

Best regards

**Comment by chrjohn** [comment]
@manureno According to reports on http://www.quickfixj.org/jira/browse/QFJ-845 it seems to work. :) Thank you.
Will merge this in due course.

**Comment by diepeglo** [comment]
Any chance to merge this to master?

**Comment by chrjohn** [comment]
Sorry, was busy. :)

**Comment by kimptoc** [comment]
Yay!  Thanks all!

**Comment by chrjohn** [comment]
There seems to be another subtle problem when not using the messages-all.jar: http://www.quickfixj.org/jira/browse/QFJ-855

**Pull request merged**
