### PR TITLE
QFJ-285 Add proxy support (compatible with SSL)

### PR DESCRIPTION
**Pull request by soliad**
This patch add support for proxy for initiator connections.
It's tested and working with and without SSL

### CODE REVIEW

**Comment by chrjohn** [comment]
Hi @soliad ,
thanks for the PR. Do you happen to have some time to put the new settings into the configuration.html page?
If not, no problem. Then I will do it later.

Best regards,
Chris.

**Comment by soliad** [comment]
Sure I'll take a look

**Comment by chrjohn** [comment]
Great, I'll see if I can still fit it into QFJ 1.6.3 which is going to be released before end of the year.

**Comment by soliad** [comment]
Hi @chrjohn 
I've added the settings in configuration.html and fixed a type for HTTP proxy (we tested it with socks with and without SSL)

I'm not sure if it will be easy to merge to QFJ 1.6 with all the SSL changes around.

Regards
Arnaud

**Comment by soliad** [comment]
My bad the branch 1.6 has all those SSL changes, so merging should be simple.

**Comment by chrjohn** [comment]
Hi @soliad ,

thanks for the doc update. Good catch on the proxy user/password typo. :)

Cheers,
Chris.

**Comment by xiaodwy** [comment]
Hello  @soliad,

Thanks for your update of the proxy feature, I have tested it and found the proxy does not compatible with the existing reconnecting logic of the initiator.
If the initiator failed to connect to the current fix server, it will try to reconnect to the next one with some intervals. But if I enable the proxy feature, the retrial will never success because the destination address of `ProxyRequest` would never be updated since the `ProxyRequest` was bound to a `ProxyConnector` which is reused for each reconnecting attempt.

Here's my configuration file of the initiator(I use quickfixj-examples/banzai for testing) with proxy settings and multiple FIX server addresses:
1. The first address ip:1111 is not in listening state, so we should get a TCP connect failure.
2. The second one is an actived echo server, I add it to test the proxy with a none-FIX server, so we should get a FIX error(without SSL) or a SSL error(with SSL).
3. The third address is a good one.
```
[default]
FileStorePath=target/data/banzai
ConnectionType=initiator
SenderCompID=BANZAI
TargetCompID=EXEC
SocketConnectHost=localhost
StartTime=00:00:00
EndTime=00:00:00
HeartBtInt=5
ReconnectInterval=5

[session]
BeginString=FIX.4.4
# test reconnect with wrong address: port 1111 is down
SocketConnectHost=172.31.1.55
SocketConnectPort=1111
# test reconnect with wrong address: port 50000 is an echo server(which is not a fix server)
SocketConnectHost1=172.31.1.55
SocketConnectPort1=50000
# test reconnect with correct address:
SocketConnectHost2=172.31.1.55
SocketConnectPort2=9880
SocketUseSSL=N
######## proxy settings for session #######
ProxyType=socks
ProxyVersion=5
ProxyHost=172.31.1.55
ProxyPort=8889
ProxyUser=testuser
ProxyPassword=password
```

Could you take a look?
Let me know if you need more information :)

Regards,
Dong

**Comment by xiaodwy** [comment]
Hi @soliad ,

I also tested the HTTP proxy with/without reconnecting to the server, but it didn't work for me. I debugged and found an issue with the code.
If you create the `HttpProxyRequest` this way:
```
        HttpProxyRequest req = new HttpProxyRequest(uri); // uri is a String
```
you will get a HTTP **GET** request, but we need a HTTP **CONNECT** request instead, so maybe we need to instance the `HttpProxyRequest` like this:
```
         HttpProxyRequest req = new HttpProxyRequest(address); // address is an InetSocketAddress
```
You can find the api doc of `HttpProxyRequest` here: https://mina.apache.org/mina-project/apidocs/
image

Here's my config file:
```
[default]
FileStorePath=target/data/banzai
ConnectionType=initiator
SenderCompID=BANZAI
TargetCompID=EXEC
SocketConnectHost=localhost
StartTime=00:00:00
EndTime=00:00:00
HeartBtInt=5
ReconnectInterval=5

[session]
BeginString=FIX.4.4
# a good FIX server address:
SocketConnectHost2=172.31.1.55
SocketConnectPort2=9880
SocketUseSSL=N
######## proxy settings for session #######
ProxyType=http
ProxyVersion=1.1
ProxyHost=172.31.1.55
ProxyPort=3128
ProxyUser=testuser
ProxyPassword=password
```

Thanks,
Dong

**Comment by soliad** [comment]
Hi @xiaodwy 

I'll take a look for the reconnect issue.
For the HTTP CONNECT, did you try with 
`HttpProxyRequest req = new HttpProxyRequest(address); // address is an InetSocketAddress` ?

Arnaud

**Comment by soliad** [comment]
Looks like an easy fix, doing some tests and hoping to do a new PR tomorrow.

**Comment by xiaodwy** [comment]
Hi @soliad ,

> For the HTTP CONNECT, did you try with
> HttpProxyRequest req = new HttpProxyRequest(address); // address is an InetSocketAddress ?

Actually I didn't try the fix with your patch, so sorry... anything wrong?
I found the HTTP proxy does not work(SOCKS proxy is good), so I captured the TCP connection to debug the issue. I noticed that the proxy request was **GET**(which is not correct), so I reviewed the code and told you my findings :)

Thanks,
Dong

**Comment by soliad** [comment]
@xiaodwy, I put a new PR https://github.com/quickfix-j/quickfixj/pull/92 that should fix those 2 issues.

**Comment by xiaodwy** [comment]
Hi @soliad ,

Thanks for your update and sorry for the late reply(I have no chance to do the test during holidays).
I have tested your fix and found some issues.
(In my testing, 9880 is good FIX port, 1111 is not exists and 50000 is an active echo server. 8889 is  socks proxy, 3128 is http proxy.)
1. The proxy works good with socks and reconnecting **without** SSL.
2. The proxy not works with SSL **enabled** in both side:
```
SocketConnectHost=172.31.1.55
SocketConnectPort=9880
SocketUseSSL=Y
ProxyType=socks
ProxyVersion=5
ProxyPort=8889
```
Got an exception on the server side:
```
javax.net.ssl.SSLHandshakeException: no cipher suites in common
...
```
3. The proxy with HTTP proxy still not work(without SSL):
```
SocketConnectHost=172.31.1.55
SocketConnectPort=9880
SocketUseSSL=N
ProxyType=http
ProxyVersion=1.1
ProxyPort=3128
```
Here're the logs:
```
[2;37m2017-01-03 15:55:09,660[55 [DEBUG] [NioProcessor-2] AbstractHttpLogicHandler.java:138 messageReceived:##   response header received:
HTTP/1.1 407 Proxy Authentication Required\r\n
Server: squid/3.4.9\r\n
Mime-Version: 1.0\r\n
Date: Tue, 03 Jan 2017 07:55:09 GMT\r\n
Content-Type: text/html\r\n
Content-Length: 3143\r\n
X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0\r\n
Vary: Accept-Language\r\n
Content-Language: en\r\n
Proxy-Authenticate: Basic realm="proxy"\r\n
X-Cache: MISS from xiaodongs-Mac-mini.local\r\n
Via: 1.1 xiaodongs-Mac-mini.local (squid/3.4.9)\r\n
Connection: keep-alive\r\n
\r\n

[2;37m2017-01-03 15:55:09,661[55 [DEBUG] [NioProcessor-2] AbstractHttpLogicHandler.java:362 decodeResponse:##   parseResponse()
[2;37m2017-01-03 15:55:09,662[55 [DEBUG] [NioProcessor-2] IoSessionEventQueue.java:77 enqueueEventIfNecessary:## ??? >> Enqueue IoSessionEvent@166cc62d - [ (0x00000001: nio socket, client, 0.0.0.0/0.0.0.0:60519 => /172.31.1.55:3128), - CLOSED event -]
[2;37m2017-01-03 15:55:09,663[55 [DEBUG] [NioProcessor-2] IoSessionEventQueue.java:61 discardSessionQueueEvents:## Event queue CLEARED
<20170103-07:55:11, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 2015 ms.)
<20170103-07:55:14, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 5024 ms.)
<20170103-07:55:17, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 8032 ms.)
<20170103-07:55:20, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 11035 ms.)
<20170103-07:55:23, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 14039 ms.)
<20170103-07:55:26, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 17048 ms.)
<20170103-07:55:29, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 20057 ms.)
<20170103-07:55:32, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 23066 ms.)
<20170103-07:55:35, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 26074 ms.)
<20170103-07:55:38, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 29084 ms.)
<20170103-07:55:41, FIX.4.4:BANZAI->EXEC, event> (Pending connection not established after 32088 ms.)
```
It seems that the HTTP proxy server(squid) closes the TCP connection immediately right after sending a 407 code to require authenticate.  I think this is a reasonable behavior(close the connection) of the HTTP proxy, so we need to handle this scenario in the code, could you take a look? 
(I have no idea to change the behavior of squid to keep the connection, so I can't do more testing on it)
image

Thanks,
Dong

**Pull request merged**
